Dev38
ZooBycH/graduation_project pull request #6
Opened 2023-01-12 21:33 UTC by ZooBycH

2023-01-13 08:58 UTC, painassasin requested changes

2023-01-13 08:58 UTC, painassasin commented on bot/admin.py
> +from bot.models import TgUser  # type: ignore
Почему стоит `# type: ignore` ?

2023-01-13 08:58 UTC, painassasin commented on bot/tests.py
> +from django.test import TestCase
Файл можно удалить

2023-01-13 08:58 UTC, painassasin commented on bot/views.py
> +        if not instance:
Эта проверка должна быть в сериализаторе, в методе валидации верификационного кода

2023-01-13 08:58 UTC, painassasin commented on bot/views.py
> +    def patch(self, request, *args, **kwargs):
Этот метод переопределять кажется было лишним

2023-01-13 08:58 UTC, painassasin commented on bot/management/commands/runbot.py
> +        verification_code = "".join(random.choice(CODE_VOCABULARY) for _ in range(12))
Это лучше было бы вынести в отдельный метод согласно принципам SOLID

2023-01-13 08:58 UTC, painassasin commented on bot/management/commands/runbot.py
> +        reply = (f"Подтвердите, пожалуйста, свой аккаунт. "
Не нужна f-строка, как и в последней части сообщения

2023-01-13 15:45 UTC, ZooBycH commented on bot/admin.py
> +from bot.models import TgUser  # type: ignore
Ругался mypy, не помогло. Там еще куча ошибок, типа " missing library stubs ", решил отложить этот вопрос.

2023-01-13 15:46 UTC, ZooBycH commented on bot/tests.py
> +from django.test import TestCase
Ок

2023-01-13 15:56 UTC, ZooBycH commented on bot/views.py
> +    def patch(self, request, *args, **kwargs):
Ок

2023-01-13 19:28 UTC, ZooBycH commented on bot/management/commands/runbot.py
> +        reply = (f"Подтвердите, пожалуйста, свой аккаунт. "
Совсем убрать f-строку здесь?

2023-01-13 19:28 UTC, ZooBycH commented on bot/management/commands/runbot.py
> +        verification_code = "".join(random.choice(CODE_VOCABULARY) for _ in range(12))
Ок

2023-01-13 20:46 UTC, ZooBycH commented on bot/management/commands/runbot.py
> +        reply = (f"Подтвердите, пожалуйста, свой аккаунт. "
Просто по другому у меня не выведет код верификации. Только через send_message разве что, а он у меня применяется в методе _send_reply.  Тогда все нужно будет переделывать:)

2023-01-13 20:46 UTC, ZooBycH commented on bot/management/commands/runbot.py
> +        reply = (f"Подтвердите, пожалуйста, свой аккаунт. "
Наверное...

2023-01-13 20:46 UTC, ZooBycH commented on bot/views.py
> +        if not instance:
Ок

2023-01-14 11:47 UTC, ZooBycH commented on bot/management/commands/runbot.py
> +        reply = (f"Подтвердите, пожалуйста, свой аккаунт. "
Понял, что требуется))) долго доходило:
reply = (
            "Подтвердите, пожалуйста, свой аккаунт.\n"
            f"Для подтверждения необходимо ввести код: {self.user.verification_code} на сайте")
так?

2023-01-14 12:12 UTC, painassasin approved these changes

2023-01-19 18:34 UTC, merged